### ISSUE TITLE
No such file or directory: '.FABulous/maxWidth.txt' while running gen_model_vpr

### ISSUE THREAD

**Issue by Asma-Mohsin** [FPGA-Research-Manchester/FABulous#104]
![image](https://github.com/FPGA-Research-Manchester/FABulous/assets/65780913/09548785-ee7f-48b0-8e1d-4b975f78e105)

**Comment by KelvinChung2000** [comment]
Have you got the `.FABulous` folder? Since this is trying to write a file to the `.FABulous` folder. 

As a side note, VPR is currently not tested. I suggest working with Yosys and Nextpnr exclusively.

**Comment by TaoBi22** [comment]
This issue should now be fixed in #108!
