### ISSUE TITLE
MaxFramesPerCol Issue?

### ISSUE THREAD

**Issue by RobB720** [FPGA-Research-Manchester/FABulous#115]
Hi,

I wanted to change the MaxFramesPerCol from 20 to a larger number so I uncommented it in the csv but this didn't seem to do anything - errors were still produced about the configMem (I think).

Digging through the code it seems that the parameter I needed to set was "FrameBitsPerColumn" - putting this in the parameter section of the Fabric.csv fixed the issue - is the demo/documentation out of date?

Many thanks,
Rob.

**Comment by KelvinChung2000** [comment]
This is a bug in the `file_parser.py`. I will get that fixed.
