### ISSUE TITLE
Error: unknown parameter "SuperTileEnable" in fabric csv at section ParametersBegin

### ISSUE THREAD

**Issue by ruck314** [FPGA-Research-Manchester/FABulous#13]
I am going through the "quick" start instructions.  Everything seems to work except for a few things in the "generating-bitstream" step:
https://fabulous.readthedocs.io/en/latest/Usage.html#generating-bitstream

1) In the current `nextpnr` submodule, `fabulous_flow.sh` is not executable.  So either the instructions should include a `chmod +x fabulous_flow.sh` step or `git add --chmod=+x fabulous_flow.sh` should be committed and pushed into nextpnr git repo

2) In the current `nextpnr` submodule, `sequential_16bit.v` does not exists.  But `sequential_16bit_en.v` does exists.  This just means the instructions for the example should be changed to `/fabulous_flow.sh sequential_16bit_en`

3) This last issue is blocking me from making progress.  I am getting a `Error: unknown parameter "SuperTileEnable" in fabric csv at section ParametersBegin` error message.  Here's my complete [log.txt](https://github.com/FPGA-Research-Manchester/FABulous/files/7928809/log.txt) file.

**Comment by TaoBi22** [comment]
Thanks for spotting these, and sorry about the delayed response! All three points should now be fixed on the master branches of the relevant repos.
