### ISSUE TITLE
fabulous-dev\fabric\verilog_output: unconnected clock warning message (possible bug)

### ISSUE THREAD

**Issue by ruck314** [FPGA-Research-Manchester/FABulous#15]
I am going through the quick start:
https://fabulous.readthedocs.io/en/latest/Usage.html#building-fabric

When I import the verilog_output files into Vivado, I am getting a warning message about the DSP_tile.v clock not being connected
```
WARNING: [VRFC 10-5021] port 'UserCLK' is not connected on this instance [XXXXX/verilog_output/DSP_tile.v:99]
```

**Comment by nguyendao-uom** [comment]
Hi @ruck314, have you fixed or still encountering the issue?

**Comment by ruck314** [comment]
@nguyendao-uom I have not fixed it.  But I could fork (or branch if you add me to the project) then investigate and try to fix it for you

**Comment by nguyendao-uom** [comment]
@ruck314 Please check, just added you to the project

**Comment by ruck314** [comment]
Closing this ticket because obsolete issue after `FABulous refactor`
