### ISSUE TITLE
Package and Publish to PyPI

### ISSUE THREAD

**Issue by mole99** [FPGA-Research-Manchester/FABulous#159]
Package FABulous and upload it to [PyPI](https://pypi.org/).

By doing so, FABulous can be easily installed, for example via `pip install fabulous-fpga`. (`fabulous` is already taken.)

In addition, a command for `fabulous-cli` can be installed, [see here for more information](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts). The FABulous CLI can then be called by entering `fabulous-cli` in your terminal.

**Comment by KelvinChung2000** [comment]
You can look into #110

**Comment by mole99** [comment]
Thanks! I did not realize there is already an effort for exactly that ^^
Should I close this issue then?
