### ISSUE TITLE
Supertiles and normal tiles

### ISSUE THREAD

**Issue by Sacoder0000** [FPGA-Research-Manchester/FABulous#251]
Hello! I am about to design a personal fabric.

What is the fundamental difference between supertile and tile? After reading the FABulous Document, it seems to me that there is only a difference in area? Is it necessary to make a supertile as long as the area is twice or more than the usual tile area? But this raises another problem:

As shown in the fabric.csv layout, it seems that every tile's area and placement is assumed, like the LUT column and Regfile column, which are one-to-one. However, after synthesis, the area of the LUT is much larger than the Regfile(eg:6000-4000umxum), which I think is likely to cause a lot of waste of area.
![abstract_tile_view](https://github.com/user-attachments/assets/a54fac89-2cfb-423a-8e00-55dbcf763e51)

**Comment by KelvinChung2000** [comment]
Supertiles are for Bels that needs more wire than what one switch matrix can provide. 

Yes, LUT tile will be much larger in size. So what you want to do is first synthesis the LUT tile to as small as possible. Then you synthesis the other tile with a fixed height that is same as the LUT tile, and try to minimise the width of the tile.

**Comment by Sacoder0000** [comment]
Couldn’t I synthesis them together? with restrict SDC constraints?

**Comment by Sacoder0000** [comment]
I will try comparing the strategies of synthesizing one by one and synthesizing all together to see which one works better.

**Comment by KelvinChung2000** [comment]
I am not sure what SDC can do. But by ensuring the LUT is smallest gives you better overall density.

**Comment by Sacoder0000** [comment]
Thanks for your advice, SDC is a timing constraints file, which i used to break timing loops in FPGA and define the frequency of CLK used in FPGA during synthesis.

**Comment by KelvinChung2000** [comment]
You can try give this paper a read https://dl.acm.org/doi/10.1145/3637543.3652874 which compares synthesis the design flat vs synthesis the design with hierarchy.

**Comment by Sacoder0000** [comment]
Wow, that's really a big help!! I needed this paper so much!!!!
