### ISSUE TITLE
Release branch currently is not protected

### ISSUE THREAD

**Issue by ruck314** [FPGA-Research-Manchester/FABulous#74]
I was looking at the different branches and noticed the release branch (`master`) does not have branch protection. So someone could potentially do a `force push` and rewrie the commit history. Branch protection can only be configured by github repo's admin in the settings.  I would strongly recommend that we add branch protection to the `master` branch
![image](https://user-images.githubusercontent.com/11821758/206862822-fe435bce-fd28-40b7-9b7f-bfc45faf7e8f.png)

**Comment by gatecat** [comment]
Good spot, this should now be enabled
![Screenshot_20221210-165733](https://user-images.githubusercontent.com/78621419/206863865-45d6e92b-be6e-44d3-94c6-66678e449487.png)
