### ISSUE TITLE
bug in run_simulation.sh

### ISSUE THREAD

**Issue by anudeepdharavathu** [FPGA-Research-Manchester/FABulous#94]
In this file /FABulous/fabric_files/FABulous_project_template_verilog/Test/run_simulation.sh

Line 3,4 are
DESIGN=counter
BITSTREAM=test_design/${DESIGN}.bin

It should be
BITSTREAM_DESIGN=sequential_16bit_en 
BITSTREAM=../user_design/${BITSTREAM_DESIGN}.bin because bitstream need to be generated for sequential_16bit_en.v not counter.v

**Comment by KelvinChung2000** [comment]
The sequential_16bit_en.v is for user examples, while the counter is for testing. If you look into `/fabric_files/FABulous_project_template_verilog/Test/test_design` you should see two test cases created.
